version: "3"

services:
  lambda:
    build: .
    environment:
      - PYTHONPATH=/var/task/src:/var/task/lib
      - PATH=/var/task/bin
      - AWS_BUCKET_NAME='aws-ap-southeast-1-391032101322-marketprice-pipe'
      - AWS_ACCESS_KEY_ID='AKIAJPDTF6XU7ZO53KHQ'
      - AWS_SECRET_ACCESS_KEY='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'
    volumes:
      - ./src/:/var/task/src/
